### ISSUE TITLE
Roll Pitch yaw rate thrust based control

### ISSUE THREAD

**Issue by raghavkhanna** [ethz-asl/dji_onboard_sdk_ros#2]
DJI apparently started supporting proper attitude control, according to their docs. Mode 14 in the [documentation](https://developer.dji.com/onboard-sdk/documentation/appendix/index.html#combinations) seems to be equivalent to the asctec sdk after figuring out the unit conversion for the thrust command.

<img width="821" alt="screen shot 2017-03-18 at 00 29 56" src="https://cloud.githubusercontent.com/assets/5816698/24066397/8b1bea94-0b72-11e7-850f-67d757311e1b.png">

Should we try this while doing the system id, @inkyusa ?

**Comment by inkyusa** [comment]
This is a great feature and aligned with our MAV team interface.
Mina has tested this and it seems to work.
In case, we are using thrust then we do need vicon for system ID whereas vertical velocity can be identified by using DJI's velocity estimation (onboard).
Therefore, all control axes can be identified by using onboard sensor without motion capture device.
If we can perform thrust sysID w/o vicon, there is no reason to use vertical velocity input. In addition, we can directly feed MPC output to N1.
