### ISSUE TITLE
rqt_copter is not open source

### ISSUE THREAD

**Issue by fmina** [ethz-asl/dji_onboard_sdk_ros#6]
@marija-p @inkyusa 
You are refering to `rqt_copter` in the Wiki. It is not open source. Instead you can use the ros service to initialize MSF.

**Comment by fmina** [comment]
Actually there is a very old version here  https://github.com/georgwi/rqt_copter 
Not sure if it will work with the current state.

**Comment by marija-p** [comment]
Hey - yes, we have noted down this as an issue to sort out. I would recommend using the service call unless there are plans to open-source.

On a less related note, I've also had problems running rqt_copter on kinetic, so I'm not sure it even makes sense to use this interface on newer releases until issues are resolved.

**Comment by inkyusa** [comment]
Good catch and I will remove rqt_copter from tutorial since it's not open source. Let's use a terminal to call "Init MSF" ros service.
Cheers,

**Comment by inkyusa** [comment]
I removed all rqt_copter related things from wiki by simply calling MSF init via terminal.
